language: php

services:
- mysql

env:
    global:
        - XDEBUG_MODE=coverage
        - CHECK_PHP_SYNTAX="false"
        - TESTS_SLURP_DBADAPTER_MYSQL_HOST="localhost"

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.2
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.3
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.4
          env: CHECK_PHP_SYNTAX="true"

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
- composer self-update
- composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
# Ensure dev packages are up to date after --prefer-lowest may have been executed.
- composer update mockery/mockery phpunit/phpunit --prefer-dist --no-interaction

script:
- composer validate --strict --no-check-lock
- php vendor/bin/phpunit -c phpunit.xml.dist --testsuite unit_tests --coverage-clover build/logs/clover.xml
- php vendor/bin/phpunit -c phpunit.xml.dist --testsuite functional_tests
- if [[ "$CHECK_PHP_SYNTAX" == "true" ]]; then php vendor/bin/php-cs-fixer fix --dry-run --verbose --diff --allow-risky=yes --no-interaction --ansi; fi;

after_success:
- travis_retry php vendor/bin/php-coveralls