name: Tests
on:
    push:
        branches: [ main, release ]
    pull_request:
        branches: [ main, release ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['7.2', '7.3', '7.4']
                composer-flag: ['--prefer-dist', '--prefer-stable --prefer-lowest', ]
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: slurp_testing
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        name: Slurp PHP ${{ matrix.php-version }} test

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Confirm PHP Version
              run: php -v

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install dependencies
              run: composer install ${{ composer-flag }} --no-progress

            - name: Run Code Style Check for PHP ${{ matrix.php-version }}
              run: composer run-script style-check
              if: matrix.php-version != '7.1'

            - name: Run tests for PHP ${{ matrix.php-version }}
              run: composer run-script test
              env:
                  TESTS_SLURP_DBADAPTER_MYSQL_HOST: 127.0.0.1
                  TESTS_SLURP_DBADAPTER_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}

            - name: Submit test coverage to Coveralls
              run: vendor/bin/php-coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: success() && matrix.php-version == '7.4' && matrix.composer-flag == '--prefer-dist'